function [ I ] = convertFromBGRRawImageData( data , w, h )

    %from http://stackoverflow.com/questions/25745141/read-image-message-from-in-ros-matlab
    I = typecast(data, 'uint8');
    I = cat(3,                              ...
                reshape(I(3:3:end),[w h])', ...
                reshape(I(2:3:end),[w h])', ...
                reshape(I(1:3:end),[w h])'  ...
           );
end

